#import '../../fragments/card.graphql'
mutation likeCardMutation($id: ID!) {
  likeCard(
    input: { id: $id }
  ) {
    card {
      id
    }
    errors {
      fullMessages
    }
  }
}

mutation likeCommentMutation($id: ID!) {
  likeComment(
    input: { id: $id }
  ) {
    comment {
      id
    }
    errors {
      fullMessages
    }
  }
}